version: '3'

services:
  app:
    container_name: chatty-server
    restart: always
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    ports:
      - '2022:2022'
    build: .
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - /usr/data/mongo:/etc/mongo:rw
    expose: 
      - 27017
    # ports:
    #   - 27017:27017
      