version: '3'

services:
  app:
    container_name: chatty-server
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    ports:
      - '2022:2022'
    build: .
    links:
      - mongo

  mongo:
    image: mongo
    expose: 
      - 27017
      